# Generated by Django 5.2.8

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('telefono', models.CharField(max_length=20, verbose_name='telefono')),
                ('mensaje', models.TextField(verbose_name='mensaje')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('reserva', 'Reserva')], default='consulta', max_length=10, verbose_name='tipo')),
                ('leida', models.BooleanField(default=False, verbose_name='leida')),
                ('atendida', models.BooleanField(default=False, verbose_name='atendida')),
                ('notas_staff', models.TextField(blank=True, help_text='Notas internas para seguimiento', verbose_name='notas del staff')),
                ('fecha_atendida', models.DateTimeField(blank=True, null=True, verbose_name='fecha atendida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='atendida por')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='vehiculos.vehiculo', verbose_name='vehiculo')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['vehiculo'], name='consultas_c_vehicul_a6c75a_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['tipo'], name='consultas_c_tipo_76af26_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['leida', 'atendida'], name='consultas_c_leida_4f5c76_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['-created_at'], name='consultas_c_created_f27e59_idx'),
        ),
    ]
