# Generated by Django 5.2.8 on 2026-01-12 06:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('parametros', '0001_initial'),
        ('vehiculos', '0002_vehiculo_tipo_vehiculo'),
        ('vendedores', '0002_email_opcional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('used', 'Reserva Usado'), ('new', 'Reserva 0KM'), ('external', 'Operacion Externa')], help_text='USED=Azul, NEW=Rojo, EXTERNAL=Amarillo', max_length=15, verbose_name='tipo de operacion')),
                ('estado', models.CharField(choices=[('pending', 'No entregado'), ('delivered', 'Entregado'), ('cancelled', 'Anulado'), ('cancelled_lost_deposit', 'Anulado con perdida de sena'), ('restructuring', 'A reestructurar')], default='pending', max_length=25, verbose_name='estado')),
                ('numero_reserva', models.CharField(editable=False, help_text='Generado automaticamente: RES-YYYY-XXXXX', max_length=20, unique=True, verbose_name='numero de reserva')),
                ('dominio', models.CharField(blank=True, help_text='Patente del vehiculo usado', max_length=10, verbose_name='dominio/patente')),
                ('numero_chasis', models.CharField(blank=True, help_text='VIN/Chasis para vehiculos 0km', max_length=50, verbose_name='numero de chasis')),
                ('proveedor', models.CharField(blank=True, help_text='Proveedor/Concesionario de origen', max_length=200, verbose_name='proveedor')),
                ('costo_patentamiento', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='costo patentamiento')),
                ('costo_flete', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='costo flete')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio venta base')),
                ('comision_vendedor', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Comision que paga el vendedor/dueno', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='comision vendedor')),
                ('comision_comprador', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Comision que paga el comprador', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='comision comprador')),
                ('gestion_credito', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='gestion de credito')),
                ('gastos_transferencia', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Transferencia para usados', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='gastos transferencia')),
                ('impuestos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='impuestos')),
                ('otros_gastos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='otros gastos')),
                ('descripcion_otros_gastos', models.TextField(blank=True, verbose_name='descripcion otros gastos')),
                ('observaciones_costos', models.TextField(blank=True, help_text='Ej: "Se cierra precio en dolares billete"', verbose_name='observaciones de costos')),
                ('fecha_entrega_pactada', models.DateField(blank=True, null=True, verbose_name='fecha entrega pactada')),
                ('entregado', models.BooleanField(default=False, verbose_name='entregado')),
                ('transferido', models.BooleanField(default=False, help_text='Transferencia de dominio realizada', verbose_name='transferido')),
                ('a_reestructurar', models.BooleanField(default=False, verbose_name='a reestructurar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='clientes.cliente', verbose_name='cliente')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('gestor_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_supervisadas', to=settings.AUTH_USER_MODEL, verbose_name='gestor/supervisor')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='parametros.moneda', verbose_name='moneda')),
                ('propietario_anterior', models.ForeignKey(blank=True, help_text='Dueno anterior del vehiculo usado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_como_propietario', to='vendedores.vendedor', verbose_name='propietario anterior')),
                ('vehiculo', models.ForeignKey(blank=True, help_text='Requerido para USED y NEW. Opcional para EXTERNAL.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='vehiculos.vehiculo', verbose_name='vehiculo')),
                ('vendedor_1', models.ForeignKey(help_text='Usuario de Autobiliaria que realizo la venta', on_delete=django.db.models.deletion.PROTECT, related_name='reservas_vendedor_1', to=settings.AUTH_USER_MODEL, verbose_name='vendedor principal')),
                ('vendedor_2', models.ForeignKey(blank=True, help_text='Para comisiones compartidas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_vendedor_2', to=settings.AUTH_USER_MODEL, verbose_name='vendedor secundario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotaReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_reservas', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='reservas.reserva', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'Nota de Reserva',
                'verbose_name_plural': 'Notas de Reserva',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GastoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Ej: Arancel, Formulario 08, Verificacion Policial', max_length=200, verbose_name='concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto')),
                ('tipo_cuenta', models.CharField(choices=[('cliente', 'A cuenta del cliente'), ('administracion', 'A cuenta administracion')], default='cliente', max_length=15, verbose_name='tipo de cuenta')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha del gasto')),
                ('metodo_pago', models.CharField(blank=True, help_text='Ej: Efectivo, Transferencia', max_length=50, verbose_name='metodo de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_administrativos', to='reservas.reserva', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'Gasto Administrativo',
                'verbose_name_plural': 'Gastos Administrativos',
                'ordering': ['tipo_cuenta', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('deposit', 'Sena'), ('cash', 'Efectivo'), ('check', 'Cheque'), ('promissory_note', 'Pagare'), ('credit', 'Credito Bancario'), ('trade_in', 'Permuta/Auto entrega')], max_length=20, verbose_name='tipo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto')),
                ('cheque_numero', models.CharField(blank=True, max_length=50, verbose_name='numero de cheque')),
                ('cheque_banco', models.CharField(blank=True, max_length=100, verbose_name='banco')),
                ('cheque_fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='fecha vencimiento')),
                ('credito_banco', models.CharField(blank=True, max_length=100, verbose_name='banco del credito')),
                ('credito_cuotas', models.PositiveIntegerField(blank=True, null=True, verbose_name='cantidad de cuotas')),
                ('credito_valor_cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor de cuota')),
                ('credito_valor_acreditado', models.DecimalField(blank=True, decimal_places=2, help_text='Monto que el banco acredita neto', max_digits=12, null=True, verbose_name='valor acreditado')),
                ('permuta_marca', models.CharField(blank=True, max_length=100, verbose_name='marca del auto entrega')),
                ('permuta_modelo', models.CharField(blank=True, max_length=100, verbose_name='modelo del auto entrega')),
                ('permuta_anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='ano del auto entrega')),
                ('permuta_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='kilometraje del auto entrega')),
                ('permuta_patente', models.CharField(blank=True, max_length=10, verbose_name='patente del auto entrega')),
                ('permuta_es_stock', models.BooleanField(default=True, help_text='True=Stock 100%%, False=50%% valor', verbose_name='es para stock')),
                ('sena_fecha', models.DateField(blank=True, null=True, verbose_name='fecha de sena')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('permuta_vehiculo', models.ForeignKey(blank=True, help_text='Si el auto entrega se ingresa al sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permutas', to='vehiculos.vehiculo', verbose_name='vehiculo de permuta')),
                ('sena_recibida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senas_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='recibida por')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pago', to='reservas.reserva', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
                'ordering': ['tipo', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['numero_reserva'], name='reservas_re_numero__186cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['tipo_operacion'], name='reservas_re_tipo_op_caa302_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado'], name='reservas_re_estado_7c17e1_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['vehiculo'], name='reservas_re_vehicul_abbf95_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['cliente'], name='reservas_re_cliente_e986e9_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['vendedor_1'], name='reservas_re_vendedo_d40733_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_entrega_pactada'], name='reservas_re_fecha_e_c64921_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['-created_at'], name='reservas_re_created_38cfbd_idx'),
        ),
    ]
