# Generated by Django 5.2.8 on 2026-01-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('dni_cuit', models.CharField(help_text='Documento unico de identificacion', max_length=20, unique=True, verbose_name='DNI/CUIT')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('telefono', models.CharField(max_length=50, verbose_name='telefono')),
                ('domicilio', models.CharField(blank=True, default='', max_length=300, verbose_name='domicilio')),
                ('notas', models.TextField(blank=True, help_text='Notas internas sobre el cliente', verbose_name='notas')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dni_cuit'], name='clientes_cl_dni_cui_23385b_idx'), models.Index(fields=['apellido', 'nombre'], name='clientes_cl_apellid_894bd6_idx')],
            },
        ),
    ]
