# Generated by Django 5.2.8 on 2025-12-31 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0002_vehiculo_tipo_vehiculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_user_id', models.CharField(help_text='ID numerico del usuario en Mercado Libre', max_length=50, verbose_name='ID de usuario ML')),
                ('ml_nickname', models.CharField(blank=True, default='', help_text='Nombre de usuario en Mercado Libre', max_length=100, verbose_name='nickname ML')),
                ('access_token', models.TextField(help_text='Token de acceso OAuth2 (expira en 6 horas)', verbose_name='access token')),
                ('refresh_token', models.TextField(help_text='Token para renovar (expira en 6 meses, un solo uso)', verbose_name='refresh token')),
                ('expires_at', models.DateTimeField(help_text='Fecha/hora de expiracion del access token', verbose_name='expira en')),
                ('scope', models.CharField(blank=True, default='', help_text='Permisos otorgados: read, write, offline_access', max_length=100, verbose_name='scope')),
                ('is_active', models.BooleanField(default=True, help_text='False si los tokens fueron invalidados', verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de conexion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ultima actualizacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ml_credential', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Credencial de Mercado Libre',
                'verbose_name_plural': 'Credenciales de Mercado Libre',
            },
        ),
        migrations.CreateModel(
            name='MLPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_item_id', models.CharField(help_text='ID unico de la publicacion en ML (ej: MLA123456789)', max_length=50, unique=True, verbose_name='ID de item ML')),
                ('ml_title', models.CharField(help_text='Titulo de la publicacion en Mercado Libre', max_length=255, verbose_name='titulo en ML')),
                ('ml_status', models.CharField(choices=[('active', 'Activa'), ('paused', 'Pausada'), ('closed', 'Cerrada'), ('under_review', 'En revision'), ('inactive', 'Inactiva')], default='active', max_length=20, verbose_name='estado en ML')),
                ('ml_price', models.DecimalField(decimal_places=2, help_text='Precio publicado en Mercado Libre', max_digits=12, verbose_name='precio en ML')),
                ('ml_currency', models.CharField(default='ARS', help_text='Codigo de moneda (ARS, USD)', max_length=3, verbose_name='moneda')),
                ('ml_permalink', models.URLField(help_text='URL directa a la publicacion en ML', max_length=500, verbose_name='link de publicacion')),
                ('ml_thumbnail', models.URLField(blank=True, default='', help_text='URL de la imagen principal en ML', max_length=500, verbose_name='imagen principal')),
                ('ml_category_id', models.CharField(blank=True, default='', help_text='ID de categoria en ML (ej: MLA1744)', max_length=20, verbose_name='categoria ML')),
                ('ml_listing_type', models.CharField(blank=True, default='', help_text='gold_special, gold_pro, gold, silver, etc.', max_length=50, verbose_name='tipo de publicacion')),
                ('patente_ml', models.CharField(blank=True, db_index=True, default='', help_text='Patente extraida del titulo/atributos para matching', max_length=10, verbose_name='patente detectada')),
                ('marca_ml', models.CharField(blank=True, default='', max_length=100, verbose_name='marca en ML')),
                ('modelo_ml', models.CharField(blank=True, default='', max_length=100, verbose_name='modelo en ML')),
                ('anio_ml', models.PositiveIntegerField(blank=True, null=True, verbose_name='ano en ML')),
                ('km_ml', models.PositiveIntegerField(blank=True, null=True, verbose_name='km en ML')),
                ('last_synced', models.DateTimeField(help_text='Ultima vez que se sincronizo con ML', verbose_name='ultima sincronizacion')),
                ('sync_error', models.TextField(blank=True, default='', help_text='Ultimo error al sincronizar', verbose_name='error de sincronizacion')),
                ('created_from_system', models.BooleanField(default=False, help_text='True si fue publicada desde autobiliaria, False si se importo', verbose_name='creada desde el sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de importacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('vehiculo', models.ForeignKey(blank=True, help_text='Vehiculo del sistema asociado a esta publicacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_publications', to='vehiculos.vehiculo', verbose_name='vehiculo vinculado')),
            ],
            options={
                'verbose_name': 'Publicacion de Mercado Libre',
                'verbose_name_plural': 'Publicaciones de Mercado Libre',
                'ordering': ['-last_synced'],
            },
        ),
        migrations.CreateModel(
            name='MLSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('import', 'Importar publicaciones'), ('create', 'Crear publicacion'), ('update', 'Actualizar publicacion'), ('pause', 'Pausar publicacion'), ('activate', 'Activar publicacion'), ('close', 'Cerrar publicacion'), ('refresh_token', 'Renovar token')], max_length=20, verbose_name='accion')),
                ('request_data', models.JSONField(blank=True, help_text='JSON enviado a la API de ML', null=True, verbose_name='datos enviados')),
                ('response_data', models.JSONField(blank=True, help_text='JSON recibido de la API de ML', null=True, verbose_name='respuesta')),
                ('success', models.BooleanField(default=False, verbose_name='exitoso')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='mercadolibre.mlpublication', verbose_name='publicacion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_sync_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_sync_logs', to='vehiculos.vehiculo', verbose_name='vehiculo')),
            ],
            options={
                'verbose_name': 'Log de sincronizacion ML',
                'verbose_name_plural': 'Logs de sincronizacion ML',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mlpublication',
            index=models.Index(fields=['ml_item_id'], name='mercadolibr_ml_item_272046_idx'),
        ),
        migrations.AddIndex(
            model_name='mlpublication',
            index=models.Index(fields=['patente_ml'], name='mercadolibr_patente_42bdc9_idx'),
        ),
        migrations.AddIndex(
            model_name='mlpublication',
            index=models.Index(fields=['ml_status'], name='mercadolibr_ml_stat_ea6ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='mlpublication',
            index=models.Index(fields=['vehiculo'], name='mercadolibr_vehicul_758ac1_idx'),
        ),
    ]
