# Generated by Django 5.2.8 on 2025-12-30 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0002_vehiculo_tipo_vehiculo'),
        ('vendedores', '0002_email_opcional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de la reunion', verbose_name='fecha')),
                ('hora', models.TimeField(help_text='Hora de la reunion', verbose_name='hora')),
                ('ubicacion', models.CharField(choices=[('falucho', 'Falucho'), ('playa_grande', 'Playa Grande')], default='falucho', max_length=20, verbose_name='ubicacion')),
                ('comprador_nombre', models.CharField(max_length=100, verbose_name='nombre del comprador')),
                ('vendedor_texto', models.CharField(blank=True, help_text='Nombre del vendedor si no esta registrado', max_length=100, verbose_name='vendedor (texto)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15, verbose_name='estado')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la reunion', verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('coordinador', models.ForeignKey(help_text='Usuario que coordina la reunion', on_delete=django.db.models.deletion.PROTECT, related_name='reuniones_coordinadas', to=settings.AUTH_USER_MODEL, verbose_name='coordinador')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reuniones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('vehiculo', models.ForeignKey(blank=True, help_text='Vehiculo relacionado con la reunion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuniones', to='vehiculos.vehiculo', verbose_name='vehiculo')),
                ('vendedor', models.ForeignKey(blank=True, help_text='Vendedor registrado en el sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuniones', to='vendedores.vendedor', verbose_name='vendedor')),
            ],
            options={
                'verbose_name': 'Reunion',
                'verbose_name_plural': 'Reuniones',
                'ordering': ['fecha', 'hora'],
                'indexes': [models.Index(fields=['fecha'], name='reuniones_r_fecha_587727_idx'), models.Index(fields=['fecha', 'hora'], name='reuniones_r_fecha_3cfd31_idx'), models.Index(fields=['ubicacion'], name='reuniones_r_ubicaci_f26296_idx'), models.Index(fields=['estado'], name='reuniones_r_estado_d4bae1_idx'), models.Index(fields=['coordinador'], name='reuniones_r_coordin_4be0af_idx'), models.Index(fields=['vendedor'], name='reuniones_r_vendedo_4b3747_idx'), models.Index(fields=['vehiculo'], name='reuniones_r_vehicul_fee4cf_idx')],
            },
        ),
    ]
