# Generated by Django 5.2.8 on 2025-12-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección')),
                ('celular', models.CharField(max_length=20, verbose_name='celular')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('tiene_cartel', models.BooleanField(default=False, verbose_name='tiene cartel')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('comentarios', models.TextField(blank=True, verbose_name='comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['-created_at'],
            },
        ),
    ]
