# Generated by Django 5.2.8 on 2025-12-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email'),
        ),
    ]
