# Generated by Django 5.2.8 on 2026-01-12 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='contenido')),
                ('fecha', models.DateField(db_index=True, verbose_name='fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_diarias', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'Nota Diaria',
                'verbose_name_plural': 'Notas Diarias',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['fecha', 'created_at'], name='notas_notad_fecha_8391c4_idx')],
            },
        ),
    ]
