# Generated by Django 5.2.8 on 2025-12-15 00:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('telefono', models.CharField(max_length=20, verbose_name='telefono')),
                ('tipo_vehiculo', models.CharField(choices=[('auto', 'Auto'), ('camioneta', 'Camioneta'), ('camion', 'Camion'), ('moto', 'Moto')], default='auto', max_length=15, verbose_name='tipo de vehiculo')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='ano')),
                ('km', models.PositiveIntegerField(default=0, verbose_name='kilometraje')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('vista', 'Vista'), ('eliminada', 'Eliminada')], default='pendiente', max_length=15, verbose_name='estado')),
                ('notas_staff', models.TextField(blank=True, help_text='Notas internas para el equipo', verbose_name='notas del staff')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='fecha de revision')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='parametros.marca', verbose_name='marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='parametros.modelo', verbose_name='modelo')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='revisada por')),
            ],
            options={
                'verbose_name': 'Publicacion de Vehiculo',
                'verbose_name_plural': 'Publicaciones de Vehiculos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagenPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen del vehiculo', upload_to='publicaciones/%Y/%m/', verbose_name='imagen')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de visualizacion', verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='publicaciones.publicacionvehiculo', verbose_name='publicacion')),
            ],
            options={
                'verbose_name': 'Imagen de publicacion',
                'verbose_name_plural': 'Imagenes de publicaciones',
                'ordering': ['orden', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='publicacionvehiculo',
            index=models.Index(fields=['estado'], name='publicacion_estado_f57435_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacionvehiculo',
            index=models.Index(fields=['email'], name='publicacion_email_92c047_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacionvehiculo',
            index=models.Index(fields=['created_at'], name='publicacion_created_5bcc07_idx'),
        ),
    ]
