# Generated by Django 5.2.8 on 2025-12-14 23:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0001_initial'),
        ('vendedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, help_text='Ej: 1.6 SE, 2.0 TDI, Sport', max_length=100, verbose_name='version')),
                ('patente', models.CharField(help_text='Patente unica del vehiculo', max_length=10, unique=True, verbose_name='patente')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='ano')),
                ('km', models.PositiveIntegerField(default=0, verbose_name='kilometraje')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='precio')),
                ('porcentaje_financiacion', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje adicional por financiacion', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='porcentaje de financiacion')),
                ('cant_duenos', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad de duenos')),
                ('vtv', models.BooleanField(default=False, verbose_name='VTV vigente')),
                ('plan_ahorro', models.BooleanField(default=False, verbose_name='plan de ahorro')),
                ('reservado', models.BooleanField(default=False, verbose_name='reservado')),
                ('vendido', models.BooleanField(default=False, verbose_name='vendido')),
                ('mostrar_en_web', models.BooleanField(default=True, verbose_name='mostrar en web')),
                ('destacar_en_web', models.BooleanField(default=False, verbose_name='destacar en web')),
                ('oportunidad', models.BooleanField(default=False, help_text='Marcar como oportunidad de compra', verbose_name='oportunidad')),
                ('oportunidad_grupo', models.BooleanField(default=False, verbose_name='oportunidad de grupo')),
                ('reventa', models.BooleanField(default=False, help_text='Es un vehiculo para reventa', verbose_name='reventa')),
                ('publicado_en_ml', models.BooleanField(default=False, verbose_name='publicado en MercadoLibre')),
                ('ml_item_id', models.CharField(blank=True, help_text='ID del item en MercadoLibre (MLA...)', max_length=50, null=True, unique=True, verbose_name='ID MercadoLibre')),
                ('ml_estado', models.CharField(blank=True, default='', help_text='active, paused, closed, etc.', max_length=20, verbose_name='estado en MercadoLibre')),
                ('ml_fecha_sync', models.DateTimeField(blank=True, null=True, verbose_name='ultima sincronizacion ML')),
                ('ml_error', models.TextField(blank=True, default='', help_text='Ultimo error de sincronizacion con ML', verbose_name='ultimo error ML')),
                ('ml_permalink', models.URLField(blank=True, default='', help_text='Link directo a la publicacion', max_length=500, verbose_name='URL en MercadoLibre')),
                ('comentario_carga', models.TextField(blank=True, help_text='Notas internas sobre el vehiculo', verbose_name='comentarios de carga')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualizacion')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete - null significa activo', null=True, verbose_name='fecha de eliminacion')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='parametros.caja', verbose_name='caja')),
                ('cargado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_cargados', to=settings.AUTH_USER_MODEL, verbose_name='cargado por')),
                ('combustible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='parametros.combustible', verbose_name='combustible')),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='parametros.condicion', verbose_name='condicion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='parametros.estado', verbose_name='estado')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='parametros.marca', verbose_name='marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='parametros.modelo', verbose_name='modelo')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='parametros.moneda', verbose_name='moneda')),
                ('segmento1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_segmento1', to='parametros.segmento', verbose_name='segmento principal')),
                ('segmento2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_segmento2', to='parametros.segmento', verbose_name='segmento secundario')),
                ('vendedor_dueno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='vendedores.vendedor', verbose_name='vendedor/dueno')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagenVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen del vehiculo', upload_to='vehiculos/%Y/%m/', verbose_name='imagen')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de visualizacion', verbose_name='orden')),
                ('es_principal', models.BooleanField(default=False, verbose_name='es imagen principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='vehiculos.vehiculo', verbose_name='vehiculo')),
            ],
            options={
                'verbose_name': 'Imagen de vehiculo',
                'verbose_name_plural': 'Imagenes de vehiculos',
                'ordering': ['orden', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['patente'], name='vehiculos_v_patente_48e85b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['marca', 'modelo'], name='vehiculos_v_marca_i_81574e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['vendido', 'reservado'], name='vehiculos_v_vendido_f03d56_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['mostrar_en_web'], name='vehiculos_v_mostrar_7919a5_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['ml_item_id'], name='vehiculos_v_ml_item_9d8788_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['deleted_at'], name='vehiculos_v_deleted_9db2cb_idx'),
        ),
    ]
