# Generated by Django 5.2.8 on 2025-12-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('auto', 'Auto'), ('camioneta', 'Camioneta'), ('camion', 'Camión'), ('moto', 'Moto')], default='auto', max_length=15, verbose_name='tipo de vehiculo'),
        ),
    ]
